# Generated by Django 2.1.7 on 2019-03-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("feeds", "0006_auto_20190107_0011")]

    operations = [
        migrations.CreateModel(
            name="IngestLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("not_responding", "Not responding"),
                        ],
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_logs",
                        to="feeds.Feed",
                    ),
                ),
            ],
        )
    ]
