# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6.7

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

variables:
  POSTGRES_DB: feedzero_ci

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V # Print out python version for debugging
  - pip install pipenv
  - pipenv install --dev

stages:
  - linting
  - tests

backend_lint:
  stage: linting
  script:
    - pipenv run flake8 .
    - pipenv run black --check .

frontend_lint:
  image: node:12.7-alpine
  stage: linting
  script:
    - cd frontend/new
    - npm install --dev
    - npm run lint --no-fix
    - npm run lint:formatting

backend_test:
  stage: tests
  services:
    - postgres:latest
  variables:
    DJANGO_SETTINGS_MODULE: config.settings.ci
    DATABASE_NAME: feedzero_ci
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_HOST: postgres
  script:
    - pipenv run pytest

frontend_test:
  image: node:12.7-alpine
  stage: tests
  script:
    - cd frontend/new
    - npm install --dev
    - npm run test:unit
