# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6.7

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: badfeed_ci

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V                                   # Print out python version for debugging
  - pip install pipenv
  - pipenv install --dev

stages:
  - linting
  - tests

pytest:
  stage: tests
  variables:
    DJANGO_SETTINGS_MODULE: config.settings.ci
    DATABASE_NAME: badfeed_ci
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_HOST: postgres
  script:
  - pipenv run pytest

flake8:
  stage: linting
  script:
  - pipenv run flake8 .
