fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: debug-statements # check for existence of pdb / ipdb/ pudb statements
