version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn -c config/gunicorn.py config.wsgi:application --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - docker.env
  rq1:
    build: .
    command: bash -c "python manage.py rqworker"
    volumes:
    - .:/code
    depends_on:
    - db
    - redis
    - web
    env_file:
      - docker.env
  rq2:
    build: .
    command: bash -c "python manage.py rqworker"
    volumes:
    - .:/code
    depends_on:
    - db
    - redis
    - web
    env_file:
      - docker.env
