version: '3'

services:
  db:
    image: postgres:11.4
  redis:
    image: redis
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - docker.env
      - secrets.env
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  rq:
    build: .
    command: bash -c "python manage.py rqworker"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
    env_file:
      - docker.env
      - secrets.env
    logging:
      options:
        max-size: "200k"
        max-file: "10"

