# Generated by Django 2.2 on 2019-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ingest", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="ingestlog",
            name="state",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("not_responding", "Not responding"),
                ],
                max_length=15,
            ),
        )
    ]
