# Generated by Django 2.0.6 on 2018-06-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("feeds", "0002_auto_20180603_1122")]

    operations = [
        migrations.CreateModel(
            name="EntryState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read"), ("saved", "Saved"), ("deleted", "Deleted")],
                        max_length=50,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="states", to="feeds.Entry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
