# Generated by Django 2.0.6 on 2018-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feeds", "0003_entrystate")]

    operations = [
        migrations.AlterField(
            model_name="entrystate",
            name="state",
            field=models.CharField(
                choices=[
                    ("unread", "Unread"),
                    ("read", "Read"),
                    ("saved", "Saved"),
                    ("deleted", "Deleted"),
                    ("pinned", "Pinned"),
                ],
                max_length=50,
            ),
        )
    ]
