name: CI

on: [push]

jobs:
  backend_lint:
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.4
    steps:
      - uses: actions/checkout@master
      - run: pip install pipenv
      - run: pipenv install --dev --ignore-pipfile
      - run: pipenv run flake8 .
      - run: pipenv run black --check .
  backend_test:
    runs-on: ubuntu-18.04
    container:
      image: python:3.7.4
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: feedzero_ci
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@master
      - run: pip install pipenv
      - run: pipenv install --dev --ignore-pipfile
      - run: pipenv run pytest
        env:
          DJANGO_SETTINGS_MODULE: config.settings.ci
          DATABASE_NAME: feedzero_ci
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: postgres
          REDIS_HOST: redis
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/docker/cli@master
      - run: docker build -t registry.gitlab.com/dammitjim/badfeed:${{ github.sha }} .
