name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
        run: python manage.py
  # test:
  #   runs-on: ubuntu-18.04
  # build:
  #   runs-on: ubuntu-18.04
  #   needs:
  #     - lint
  #     - test
