name: CI

on: [push]

services:
  postgresql:
    image: postgresql
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  redis:
    image: redis
    ports:
      - 6379/tcp

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: peaceiris/actions-pipenv@v1.0.0
      - name: Install dependencies
        run: pipenv install --dev
      - name: flake8
        run: pipenv run flake8 .


